[package]
name = "kaps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.9"
tui = { version = "0.16.0", features = ["crossterm"] }
crossterm = "0.22.1"
dirs = "4.0.0"
sysinfo = "0.22.0"